export const cars = [
  {
    id: 1001,
    category: "sport",
    name: "Koenigsegg",
    firstPrice: "99.00",
    secondPrice: "0",
    FuelVolume: "90",
    gearbox: "Manual",
    Capacity: "2",
    popular: true,
    image: "car1",
  },
  {
    id: 1002,
    category: "sport",
    name: "Nissan GT - R",
    firstPrice: "80.00",
    secondPrice: "100.00",
    FuelVolume: "80",
    gearbox: "Manual",
    Capacity: "2",
    popular: true,
    image: "car2",
  },
  {
    id: 1003,
    category: "sedan",
    name: "Rolls - Royce",
    firstPrice: "96.00",
    secondPrice: "0",
    FuelVolume: "70",
    gearbox: "Manual",
    Capacity: "4",
    popular: true,
    image: "car3",
  },
  {
    id: 1004,
    category: "sport",
    name: "Nissan GT - R",
    firstPrice: "80.00",
    secondPrice: "100.00",
    FuelVolume: "80",
    gearbox: "Manual",
    Capacity: "2",
    popular: true,
    image: "car4",
  },
  {
    id: 1005,
    category: "SUV",
    name: "All New Rush",
    firstPrice: "72.00",
    secondPrice: "80.00",
    FuelVolume: "70",
    gearbox: "Manual",
    Capacity: "6",
    popular: false,
    image: "car5",
  },
  {
    id: 1006,
    category: "SUV",
    name: "CR - V",
    firstPrice: "80.00",
    secondPrice: "0",
    FuelVolume: "80",
    gearbox: "Manual",
    Capacity: "6",
    popular: false,
    image: "car6",
  },
  {
    id: 1007,
    category: "SUV",
    name: "All New Terios",
    firstPrice: "74.00",
    secondPrice: "0",
    FuelVolume: "90",
    gearbox: "Manual",
    Capacity: "6",
    popular: false,
    image: "car7",
  },
  {
    id: 1008,
    category: "SUV",
    name: "CR - V",
    firstPrice: "80.00",
    secondPrice: "0",
    FuelVolume: "80",
    gearbox: "Manual",
    Capacity: "6",
    popular: false,
    image: "car8",
  },
  {
    id: 1009,
    category: "SUV",
    name: "All New Rush",
    firstPrice: "72.00",
    secondPrice: "80.00",
    FuelVolume: "70",
    gearbox: "Manual",
    Capacity: "6",
    popular: false,
    image: "car5",
  },
  {
    id: 1010,
    category: "SUV",
    name: "CR - V",
    firstPrice: "80.00",
    secondPrice: "0",
    FuelVolume: "80",
    gearbox: "Manual",
    Capacity: "6",
    popular: false,
    image: "car6",
  },
  {
    id: 1011,
    category: "SUV",
    name: "All New Terios",
    firstPrice: "74.00",
    secondPrice: "0",
    FuelVolume: "90",
    gearbox: "Manual",
    Capacity: "6",
    popular: false,
    image: "car7",
  },
  {
    id: 1012,
    category: "SUV",
    name: "CR - V",
    firstPrice: "80.00",
    secondPrice: "0",
    FuelVolume: "80",
    gearbox: "Manual",
    Capacity: "6",
    popular: false,
    image: "car8",
  },
];
